[package]
name = "hello_rust"
version = "0.1.0"
edition = "2021"
authors = ["pengcc <pcc9109@gmail.com>"]
license = "MIT"
description = "This is a demo"
keywords = ["demo", "rust"]
homepage = "https://github.com/pengcc/hello-rust"

[lib]
crate-type = ["cdylib"]
bench = false